# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=38)),
                ('description', models.CharField(max_length=38)),
                ('start_date', models.DateTimeField(max_length=38)),
                ('end_date', models.DateTimeField(max_length=38)),
                ('password', models.CharField(max_length=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=38)),
                ('last_name', models.CharField(max_length=38)),
                ('user_name', models.CharField(max_length=38)),
                ('password', models.CharField(max_length=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.User'),
        ),
    ]
