# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20170623_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='password',
        ),
    ]
