# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_remove_trip_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='join',
            field=models.CharField(default='false', max_length=8),
        ),
    ]
